#!/bin/bash
# Easy Install script for Recalboy
# kjbstar - https://github.com/kjbstar/recalboy
# Create Apache vhost from : https://github.com/RoverWire/virtualhost/blob/master/virtualhost.sh

LATEST_RELEASE="0.1.2"
IP="$(hostname -I)"
ANSWER_DEFAULT="y"
RECALBOY_DEFAULT_PATH="/var/www/html"

RED=`tput setaf 1`
GREEN=`tput setaf 2`
BLUE=`tput setaf 4`
MAGENTA=`tput setaf 5`
YELLOW=`tput setaf 3`
RESET=`tput sgr0`

 
echo ""
echo ""
echo "${YELLOW}####################################################################"
echo "################### RECALBOY EASY INSTALL WIZARD ###################"
echo "####################################################################${RESET}"
echo ""
echo ""
echo "${MAGENTA}############################"
echo "PART 1 : Server requirements"
echo "############################${RESET}"
echo "${GREEN}We will now install, if necessary, Apache 2, PHP 5, Curl, Memcached, Unzip, and Git${RESET}"
read -p "${RED}Are you ready to proceed ?${RESET} [$ANSWER_DEFAULT/N]: " START_WIZARD
START_WIZARD="${START_WIZARD:-$ANSWER_DEFAULT}"
echo ""
echo ""
if [[ $START_WIZARD =~ ^([yY][eE][sS]|[yY])+$ ]] ; then

	sudo apt-get update
	echo ""
	echo ""
	sudo apt-get install apache2 php5 php5-curl curl php5-memcached memcached git unzip
	echo ""
	echo ""
	a2enmod rewrite
	service apache2 restart

else
	exit;

fi
echo ""
echo ""
echo ""
echo "${MAGENTA}#########################################"
echo "PART 2 : Setting up Recalboy VirtualHost"
echo "#########################################${RESET}"
echo "${GREEN}Do you already have any other websites configured with Apache on this machine ?"
echo "If yes, don't worry the path is customisable."
echo "If no or if you don't understand, don't think, press enter to all questions, and let the magic happen :)${RESET}"
echo ""
echo ""
read -p "${RED}Do you want me to auto-configure Recalboy's VirtualHost in Apache ?${RESET} [$ANSWER_DEFAULT/N]: " CONFIG_APACHE
CONFIG_APACHE="${CONFIG_APACHE:-$ANSWER_DEFAULT}"

if [[ $CONFIG_APACHE =~ ^([yY][eE][sS]|[yY])+$ ]] ; then
	
	echo ""
	echo ""
	echo "${GREEN}Choose Recalboy's files location. ${RESET}"
	read -p "${RED}If you don't know and/or don't already have any VirtualHost configured here, just press enter${RESET} [$RECALBOY_DEFAULT_PATH]: " RECALBOY_PATH
	RECALBOY_FINAL_PATH="${RECALBOY_PATH:-$RECALBOY_DEFAULT_PATH}/public"

	if [[ $RECALBOY_FINAL_PATH = "/var/www/html/public" ]] ; then
		sudo rm /etc/apache2/sites-enabled/000-default.conf
		APACHE_CONF="000-default.conf"
	else
		if ! [ -d $RECALBOY_PATH ]; then
			### create the directory
			sudo mkdir $RECALBOY_PATH
			### give permission to root dir
			sudo chmod 755 $RECALBOY_PATH
			echo "${RED}Sorry, there's a bug at the end of the script. My bad, I don't know how to take a value outside the 'if loop'. So you must use default path to continue."
		fi
		APACHE_CONF="recalboy.conf"
	fi

	FILE="/etc/apache2/sites-enabled/${APACHE_CONF}"

	sudo touch ${FILE}
	sudo chmod 775 ${FILE}

	if ! echo "#### Generated by Recalboy Easy Install Script
	<VirtualHost *:80>
		ServerName recalboy.local
		ServerAdmin your@email.com
		DocumentRoot ${RECALBOY_FINAL_PATH}

		<Directory \"${RECALBOY_FINAL_PATH}\">
			AllowOverride All
			Order allow,deny
			Allow from all
			Options FollowSymlinks
		</Directory>

		ErrorLog /var/log/apache2/recalboy.error.log
		CustomLog /var/log/apache2/recalboy.access.log combined
	</VirtualHost>" > ${FILE}
	then
		echo ""
		echo "Error creating virtual host !"
		exit;
	else
		echo ""
		echo "Virtual Host created !"
	fi

	if ! echo "127.0.0.1		recalboy.local" >> /etc/hosts
	then
		echo ""
		echo "Not able to write in /etc/hosts, please run this script as sudo"
		exit;
	else
		echo ""
		echo "Host added to /etc/hosts file"
	fi

	echo ""
	echo ""
	/etc/init.d/apache2 reload
	echo ""
	echo ""
	echo "${GREEN}Virtual Host fully configured, you can access on${RESET} http://recalboy.local ${GREEN}or${RESET} http://${IP} ${GREEN}in your browser.${RESET}"
	echo "${GREEN}If you have customised the VirtualHost path, to access from another machine, add${RESET} ${IP} recalboy.local ${GREEN} to your hosts file.${RESET}"
	echo ""
	echo ""


else
	echo ""
	echo "Ok, you're an adult, I let you do this by yourself."

fi

echo ""
echo ""
echo ""
echo "${MAGENTA}#########################################"
echo "PART 3 : Get Composer"
echo "#########################################${RESET}"
echo "${GREEN}If you don't have Composer, I will install it for you"
echo ""
echo ""
read -p "${RED}Do you want to install Composer ?${RESET} [$ANSWER_DEFAULT/N]: " INSTALL_COMPOSER
INSTALL_COMPOSER="${INSTALL_COMPOSER:-$ANSWER_DEFAULT}"

if [[ $INSTALL_COMPOSER =~ ^([yY][eE][sS]|[yY])+$ ]] ; then
	
	php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
	php -r "if (hash_file('SHA384', 'composer-setup.php') === '669656bab3166a7aff8a7506b8cb2d1c292f042046c5a994c43155c0be6190fa0355160742ab2e1c88d40d5be660b410') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
	php composer-setup.php
	php -r "unlink('composer-setup.php');"
	sudo mv composer.phar /usr/local/bin/composer

	echo ""
	echo "${GREEN}Hooray! Composer has been installed and moved to /usr/local/bin."
	echo "Use it from anywhere with: composer${RESET}"
fi


echo ""
echo ""
echo ""
echo "${MAGENTA}#########################################"
echo "PART 4 : Install Recalboy !"
echo "#########################################${RESET}"
echo "${GREEN}Time to install latest release of Recalboy !"
echo ""
read -p "${RED}Ready to install Recalboy v${LATEST_RELEASE} ?${RESET} [$ANSWER_DEFAULT/N]: " INSTALL_RECALBOY
INSTALL_RECALBOY="${INSTALL_RECALBOY:-$ANSWER_DEFAULT}"

if [[ $INSTALL_RECALBOY =~ ^([yY][eE][sS]|[yY])+$ ]] ; then
	
	echo ""
	echo "${YELLOW}Downloading latest release...${RESET}"
	wget "https://github.com/kjbstar/recalboy/archive/v${LATEST_RELEASE}.zip"
	echo ""
	echo "${YELLOW}Unzipping...${RESET}"
	unzip v${LATEST_RELEASE}.zip -d ${RECALBOY_DEFAULT_PATH}
	echo ""
	echo "${YELLOW}Moving files into Virtual Host${RESET}"
	mv ${RECALBOY_DEFAULT_PATH}/recalboy-${LATEST_RELEASE}/* ${RECALBOY_DEFAULT_PATH}/
	mv ${RECALBOY_DEFAULT_PATH}/recalboy-${LATEST_RELEASE}/.[!.]* ${RECALBOY_DEFAULT_PATH}/
	echo ""
	echo "${YELLOW}Deleting Zip file...${RESET}"
	rmdir ${RECALBOY_DEFAULT_PATH}/recalboy-${LATEST_RELEASE}
	rm v${LATEST_RELEASE}.zip
	echo "."
	echo "."
	echo "."
	echo "."
	echo "."
	echo "."
	echo "${YELLOW}Launching Installation of Recalboy. It may take some time, so please be patient${RESET}"
	composer install -d ${RECALBOY_DEFAULT_PATH}
	composer update -d ${RECALBOY_DEFAULT_PATH} --no-scripts
	mkdir ${RECALBOY_DEFAULT_PATH}/storage/framework && chmod 777 ${RECALBOY_DEFAULT_PATH}/storage/framework
	mkdir ${RECALBOY_DEFAULT_PATH}/storage/framework/cache && chmod 777 ${RECALBOY_DEFAULT_PATH}/storage/framework/cache
	mkdir ${RECALBOY_DEFAULT_PATH}/storage/framework/views && chmod 777 ${RECALBOY_DEFAULT_PATH}/storage/framework/views
	echo ""
	echo ""
	echo ""
	echo "${GREEN}BRAVO ! Recalboy has been installed."
fi

echo "Last but not least, I must activate the Retroarch Network Commands on your Recalbox."
read -p "Please turn on your Recalbox, and enter its IP (192.168.X.X):${RESET} " IP_RECALBOX

sed -i "s/\(RECALBOX_IP *= *\).*/\1${IP_RECALBOX}/" ${RECALBOY_DEFAULT_PATH}/.env

curl -L http://recalboy.local/config/check/retroarch/networkcommands

echo ""
echo ""
echo ""
echo "${GREEN}All done ! You can now use Recalboy.${RESET}"
echo "http://${IP}"
echo "${GREEN}or${RESET}"
echo "http://recalboy.local"
echo ""