#!/bin/bash
# Easy Provisionning script for Recalboy
# kjbstar - https://github.com/kjbstar/recalboy
# Create Apache vhost from : https://github.com/RoverWire/virtualhost/blob/master/virtualhost.sh

LATEST_RELEASE="0.3"
IP="$(hostname -I)"
ANSWER_DEFAULT="y"
RECALBOY_DEFAULT_PATH="/var/www/html"

RED=`tput setaf 1`
GREEN=`tput setaf 2`
BLUE=`tput setaf 4`
MAGENTA=`tput setaf 5`
YELLOW=`tput setaf 3`
RESET=`tput sgr0`

 
echo ""
echo ""
echo "${YELLOW}####################################################################"
echo "################### RECALBOY EASY INSTALL - PROVISIONNING ###########"
echo "####################################################################${RESET}"
echo ""
echo ""
echo "${MAGENTA}############################"
echo "PART 1 : Server requirements"
echo "############################${RESET}"
echo ""
echo ""

	sudo apt-get update
	sudo apt-get install apache2 php5 php5-curl curl unzip
	echo ""
	echo ""
	a2enmod rewrite
	service apache2 restart

echo ""
echo ""
echo ""
echo "${MAGENTA}#########################################"
echo "PART 2 : Setting up Recalboy VirtualHost"
echo "#########################################${RESET}"
echo ""
echo ""

	sudo rm /etc/apache2/sites-enabled/000-default.conf
	APACHE_CONF="000-default.conf"

	FILE="/etc/apache2/sites-enabled/${APACHE_CONF}"

	sudo touch ${FILE}
	sudo chmod 775 ${FILE}

	if ! echo "#### Generated by Recalboy Easy Install Script
	<VirtualHost *:80>
		ServerName recalboy.local
		ServerAdmin your@email.com
		DocumentRoot /var/www/html/public

		<Directory \"/var/www/html/public\">
			AllowOverride All
			Order allow,deny
			Allow from all
			Options FollowSymlinks
		</Directory>

		ErrorLog /var/log/apache2/recalboy.error.log
		CustomLog /var/log/apache2/recalboy.access.log combined
	</VirtualHost>" > ${FILE}
	then
		echo ""
		echo "Error creating virtual host !"
		exit;
	else
		echo ""
		echo "Virtual Host created !"
	fi

	if ! echo "127.0.0.1		recalboy.local" >> /etc/hosts
	then
		echo ""
		echo "Not able to write in /etc/hosts, please run this script as sudo"
		exit;
	else
		echo ""
		echo "Host added to /etc/hosts file"
	fi

	echo ""
	echo ""
	/etc/init.d/apache2 reload
	echo ""
	echo ""
	echo "${GREEN}Virtual Host fully configured, you can access on${RESET} http://recalboy.local ${GREEN}or${RESET} http://${IP} ${GREEN}in your browser.${RESET}"
	echo "${GREEN}If you have customised the VirtualHost path, to access from another machine, add${RESET} ${IP} recalboy.local ${GREEN} to your hosts file.${RESET}"
	echo ""
	echo ""

echo ""
echo ""
echo ""
echo "${MAGENTA}#########################################"
echo "PART 3 : Get Composer"
echo "#########################################${RESET}"
echo ""
echo ""

	
	EXPECTED_SIGNATURE=$(wget -q -O - https://composer.github.io/installer.sig)
	php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
	ACTUAL_SIGNATURE=$(php -r "echo hash_file('SHA384', 'composer-setup.php');")

	if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
	then
	    >&2 echo 'ERROR: Invalid installer signature'
	    rm composer-setup.php
	    exit 1
	fi

	php composer-setup.php --quiet
	RESULT=$?
	rm composer-setup.php	
	sudo mv composer.phar /usr/local/bin/composer

	echo ""
	echo "${GREEN}Hooray! Composer has been installed and moved to /usr/local/bin."
	echo "Use it from anywhere with: composer${RESET}"


echo ""
echo ""
echo ""
echo "${MAGENTA}#########################################"
echo "PART 4 : Install Recalboy !"
echo "#########################################${RESET}"
echo "${GREEN}Time to install latest release of Recalboy !"
echo ""
read -p "${RED}Ready to install Recalboy v${LATEST_RELEASE} ?${RESET} " 

	
	echo ""
	echo "${YELLOW}Downloading latest release...${RESET}"
	wget "https://github.com/kjbstar/recalboy/archive/v${LATEST_RELEASE}.zip"
	echo ""
	echo "${YELLOW}Unzipping...${RESET}"
	unzip v${LATEST_RELEASE}.zip -d ${RECALBOY_DEFAULT_PATH}
	echo ""
	echo "${YELLOW}Moving files into Virtual Host${RESET}"
	mv ${RECALBOY_DEFAULT_PATH}/recalboy-${LATEST_RELEASE}/* ${RECALBOY_DEFAULT_PATH}/
	mv ${RECALBOY_DEFAULT_PATH}/recalboy-${LATEST_RELEASE}/.[!.]* ${RECALBOY_DEFAULT_PATH}/
	echo ""
	echo "${YELLOW}Deleting Zip file...${RESET}"
	rmdir ${RECALBOY_DEFAULT_PATH}/recalboy-${LATEST_RELEASE}
	rm v${LATEST_RELEASE}.zip
	echo "."
	echo "."
	echo "."
	echo "."
	echo "."
	echo "."
	echo "${MAGENTA}Launching Installation of Recalboy. It may take some time, so please be patient.${RESET}"
	echo "."
	echo "."
	echo "."
	echo "."
	echo "."
	echo "."
	composer install -d ${RECALBOY_DEFAULT_PATH}
	composer update -d ${RECALBOY_DEFAULT_PATH} --no-scripts
	echo ""
	echo ""
	echo ""
	echo "${GREEN}BRAVO ! Recalboy has been installed."


echo "Last but not least, I must activate the Retroarch Network Commands on your Recalbox."
echo "${MAGENTA}Press enter and activate this option by yourself in Retroarch menu if your Recalbox is a fresh install"
echo "or if you have a very customised retroarchcustom.cfg . Because this process may fail, and you would have to"
echo "delete retroarchcustom.cfg , and let Recalbox generate a new one.${RESET} Coming soon : better management of this activation."
echo ""
echo ""
read -p "Please turn on your Recalbox, and enter its IP (192.168.X.X):${RESET} " IP_RECALBOX

sed -i "s/\(RECALBOX_IP *= *\).*/\1${IP_RECALBOX}/" ${RECALBOY_DEFAULT_PATH}/.env

curl -L http://recalboy.local/config/check/retroarch/networkcommands

echo ""
echo ""
echo ""
echo "${GREEN}All done ! You can now use Recalboy.${RESET}"
echo "http://${IP}"
echo "${GREEN}or${RESET}"
echo "http://recalboy.local"
echo ""
echo "${GREEN}Configuration URL is here:${RESET}"
echo "http://${IP}/config"
echo "${GREEN}or here:${RESET}"
echo "http://recalboy.local/config"
echo ""
echo "${GREEN}Useful to setup Demo Mode, Upload, etc...${RESET}"
echo ""
